replicaCount: 2

image:
  repository: andrewlimit/fcsapp
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

container:
  port: 8080

config:
  server:
    host: "0.0.0.0"
    port: 8080
    shutdownTimeout: "5s"

  database:
    port: 5432
    sslMode: "disable"
    maxOpenConns: 25
    maxIdleConns: 25
    connMaxLifetime: "5m"
    pingTimeout: "5s"
    replicas: []

  session:
    ttl: "24h"
    cleanupInterval: "5s"

volumeMounts:
  - name: app-config
    mountPath: /home/fcstask-admin/config/config.yaml
    subPath: config.yaml
    readOnly: true

volumes:
  - name: app-config
    secret:
      secretName: fcsapp-config

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false
